language: node_js
node_js:
  - 5.11
  - 6
  - 6.1
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgif-dev
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - g++-4.8
env:
  - CXX=g++-4.8
install:
  - npm install
script:
  - npm run lint
  - npm test
after_success:
  - npm run build
deploy:
  provider: npm
  email: "nonamea774@gmail.com"
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    node: '6'
